package io.github.repir.Repository;

import java.util.ArrayList;
import java.util.HashMap;
import io.github.repir.EntityReader.MapReduce.TermEntityKey;
import io.github.repir.EntityReader.MapReduce.TermEntityValue;
import io.github.repir.EntityReader.Entity;
import io.github.repir.tools.Content.StructuredFileIntID;

/**
 * A AutoTermDocumentFeature that is configured for a Repository is automatically
 * generated by the standard Repository builder in apps.Repository.Build. Other
 * TermDocumentFeatures have to be build manually.
 * @author jeroen
 * @param <F>
 * @param <C> 
 */
public abstract class AutoTermDocumentFeature<F extends StructuredFileIntID, C> extends TermDocumentFeature<F, C> implements ReducibleFeature {

   HashMap<String, Integer> docs;

   public AutoTermDocumentFeature(Repository repository, String field) {
      super(repository, field);
   }

   public void setDocs(HashMap<String, Integer> docs) {
      this.docs = docs;
      termid = 0;
   }

   public void writereduce(TermEntityKey key, Iterable<TermEntityValue> values) {
      reduceInput(key, values);
   }

   @Override
   public void openRead() {
      super.openRead();
      if (termid >= 0) {
         find(termid);
         docid = -1;
      }
   }

   @Override
   public void startReduce(int partition) {
      setPartition(partition);
      getFile().openWrite();
   }

   @Override
   public void finishReduce() {
      getFile().closeWrite();
   }

   abstract public void writeMapOutput(TermEntityValue writer, Entity doc, ArrayList<Integer> pos);

}
