package io.github.repir.Repository;

/**
 * DictionaryFeatures tat are configured for a Repository are automatically 
 * generated by the standard Vocabulary builder apps.Vocabulary.Build. The default
 * process is to first build all DictionaryFeatures for a Repository, and then do
 * a second pass to extract the other features from the collection and store these
 * in the Repository using apps.Repository.Build.
 * @author jer
 */
public interface DictionaryFeature {

   public void reduceInput(int id, String term, long cf, long df);

   public void startReduce(long cf, int df);

   public void finishReduce();
}
